default:
    path: /
    controller: App\Controller\DefaultController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index

promotion:
    path: /promotion
    controller: App\Controller\PromotionController::index

aboutus:
  path: /aboutus
  controller: App\Controller\AboutusController::index

address:
  path: /address
  controller: App\Controller\AddressController::index
